"""Alignment between PyMARE and metafor on tau^2 and the statistics derived from Q.

:mod:`pymare.tests.test_metafor_alignment` covers the fixed-effect inference path
-- what ``rma.uni`` reports under each ``test`` setting, given a tau^2. This
module covers the rest of what ``rma.uni`` reports and PyMARE also computes:

-   Cochran's ``Q`` and its p-value, from
    :meth:`~pymare.results.MetaRegressionResults.get_heterogeneity_stats`.
-   ``I^2`` and ``H``, from the same method.
-   The Q-profile confidence interval for tau^2, from
    :meth:`~pymare.results.MetaRegressionResults.get_re_stats`.
-   The tau^2 point estimate itself, for each estimator PyMARE and metafor share.

The reference values are pinned in ``data/metafor_reference.json`` alongside the
ones the other module reads, and regenerated by the same script. Both come from
the same 180-case grid; the quantities here do not depend on metafor's ``test``
setting, which :func:`test_heterogeneity_does_not_depend_on_the_correction`
checks rather than assumes before the rest of the module drops down to the 60
distinct cases.

What agrees, and how exactly, is recorded in ``validation/metafor/README.md``.
Three divergences are pinned down here rather than merely tolerated, each by a
test that asserts *why* the two differ instead of how much:

-   ``I^2`` and ``H``: PyMARE always reports the Q-based definition of
    :footcite:t:`higgins2002quantifying`. metafor reports that pair only for
    ``FE`` and ``DL`` -- where it coincides with tau^2 / (tau^2 + v_t) -- and
    the tau^2-based pair otherwise. See
    :func:`test_i2_and_h_are_the_q_based_definition`.
-   :class:`~pymare.estimators.Hedges` tau^2: PyMARE subtracts the mean sampling
    variance, metafor subtracts ``tr(PV) / (K - P)``. The two are equal when the
    only predictor is the intercept and differ otherwise. See
    :func:`test_hedges_tau2_divergence_is_the_trace_term`.
-   ``ML`` and ``REML`` tau^2: both profile the likelihood numerically, to
    different tolerances, and on one cell of the grid they stop on opposite
    sides of the tau^2 = 0 boundary. See :data:`RTOL_PROFILED` and
    :data:`ML_BOUNDARY_CASE`.

References
----------
.. footbibliography::

"""

import numpy as np
import pytest

from pymare.estimators import (
    DerSimonianLaird,
    Hedges,
    VarianceBasedLikelihoodEstimator,
    WeightedLeastSquares,
)
from pymare.tests.test_metafor_alignment import MODELS, build_dataset, case_id
from pymare.tests.utils import load_metafor_reference

pytestmark = pytest.mark.metafor

REFERENCE = load_metafor_reference()

#: Tolerance for the quantities both implementations reach in closed form. Q is
#: a weighted residual sum of squares on either side and I^2 and H are algebraic
#: functions of it, so they agree to a few multiples of machine epsilon; the
#: p-value is the loosest at 1.5e-13, being a chi-squared tail.
RTOL = 1e-11

#: Tolerance for the Q-profile interval. Both implementations invert the same Q
#: to a root -- ``scipy.optimize.brentq`` here, ``uniroot`` there -- and agree to
#: 1.3e-13. Note that the reference is generated with ``confint``'s tolerance
#: tightened: its default is ``uniroot``'s ``.Machine$double.eps^0.25``, about
#: 1.2e-4 relative, so pinning the default would check PyMARE against metafor's
#: display precision rather than against the bound it solves for.
RTOL_PROFILE = 1e-11

#: Tolerance for tau^2 where *both* implementations profile a likelihood
#: numerically. Worst observed 2.7e-5 relative, on ``extreme_k10`` with one
#: moderator under ``REML``: PyMARE profiles to ``xtol=1e-6`` on tau^2 and
#: metafor runs its own optimizer to its own tolerance, so this bound measures
#: the two search tolerances and not the objective. Tightening it is a change to
#: :func:`~pymare.stats.bounded_scalar_min`, not to this test.
RTOL_PROFILED = 1e-4

#: Absolute companion to :data:`RTOL_PROFILED`, for the cells that land on the
#: tau^2 = 0 boundary. On ``equal_k5`` with two moderators metafor's ``ML``
#: search stops at 1.3e-7 where PyMARE's returns exactly zero: the same answer
#: to seven decimals, but no relative tolerance can say so against a zero.
ATOL_PROFILED = 1e-6

#: The one cell in the grid where the two ``ML`` searches land on genuinely
#: different sides of the tau^2 = 0 boundary: metafor reports 0 and PyMARE
#: 0.0114, which is a real difference rather than a tolerance. A profile
#: likelihood is flattest at the boundary, and ``extreme_k10`` is the design
#: whose weights are most unequal.
#: :func:`test_ml_boundary_case_is_the_only_disagreement` keeps this from
#: silently growing into a list.
ML_BOUNDARY_CASE = ("extreme_k10", "one")

#: The estimators compared, in metafor's names. Keyed the same way as
#: ``methods`` in ``validation/metafor/run_metafor.R``.
ESTIMATORS = {
    "FE": lambda: WeightedLeastSquares(tau2=0.0),
    "DL": DerSimonianLaird,
    "HE": Hedges,
    "ML": lambda: VarianceBasedLikelihoodEstimator(method="ML"),
    "REML": lambda: VarianceBasedLikelihoodEstimator(method="REML"),
}

#: metafor ``method`` values whose ``I^2`` and ``H^2`` are the Q-based pair, and
#: which PyMARE can therefore be compared against on those two. For ``DL`` the
#: coincidence is an identity rather than a special case: DL's tau^2 is
#: ``(Q - df) / sum(diag(P))`` and metafor's typical variance is
#: ``df / sum(diag(P))``, so ``tau^2 / v_t`` reduces to ``(Q - df) / df``.
Q_BASED_METHODS = ("FE", "DL")

#: One case per (design, model, tau^2 estimator). The quantities in this module
#: do not depend on metafor's ``test``, so the grid collapses by a factor of
#: three; ``test="z"`` is the slice kept because it is the uncorrected one.
CASES = [case for case in REFERENCE["cases"] if case["test"] == "z"]

RANDOM_EFFECT_CASES = [case for case in CASES if case["method"] != "FE"]

HEDGES_CASES = [case for case in CASES if case["method"] == "HE"]

PROFILED_CASES = [case for case in CASES if case["method"] in ("ML", "REML")]


def fit(frame, case):
    """Fit the estimator metafor's ``method`` names to this case's design."""
    return ESTIMATORS[case["method"]]().fit_dataset(build_dataset(frame, case)).summary()


def design_arrays(frame, case):
    """Return ``(y, v, X)`` for one case, with the intercept already in ``X``."""
    rows = frame[frame["case"] == case["design"]]
    y = rows["y"].to_numpy()
    columns = MODELS[case["model"]]
    X = np.column_stack([np.ones_like(y)] + [rows[name].to_numpy() for name in columns])
    return y, rows["v"].to_numpy(), X


def test_heterogeneity_does_not_depend_on_the_correction():
    """The quantities below must be the same under all three ``test`` settings.

    Every other test in this module reads only the ``test="z"`` slice of the
    pinned grid. That is sound only because ``rma.uni``'s heterogeneity block and
    its ``confint`` do not move when the small-sample correction is switched on
    -- the correction rescales the coefficient covariance and nothing else. This
    asserts that from the reference itself, so a future metafor that did change
    one of them would be caught here rather than hidden by the slicing.
    """
    grouped = {}
    for case in REFERENCE["cases"]:
        key = (case["design"], case["model"], case["method"])
        recorded = tuple(
            case[field] for field in ("QE", "QEp", "I2", "H2", "tau2", "tau2_ci_lb", "tau2_ci_ub")
        )
        grouped.setdefault(key, set()).add(recorded)

    assert len(grouped) == len(CASES)
    varying = sorted(key for key, values in grouped.items() if len(values) > 1)
    assert not varying, varying


@pytest.mark.parametrize("case", CASES, ids=[case_id(case) for case in CASES])
def test_q_matches_metafor(case, metafor_dataset):
    """Cochran's Q and its p-value must be metafor's ``QE`` and ``QEp``.

    Both are properties of the design rather than of the estimator -- the Q
    PyMARE reports is always taken at tau^2 = 0, and so is metafor's -- so this
    runs over every estimator in the grid and expects the same numbers from each.
    """
    stats = fit(metafor_dataset, case).get_heterogeneity_stats()
    assert np.allclose(np.ravel(stats["Q"]), case["QE"], rtol=RTOL)
    assert np.allclose(np.ravel(stats["p(Q)"]), case["QEp"], rtol=RTOL)
    # logp(Q) exists so that a p-value past the underflow point is still usable.
    # None of these designs is anywhere near it, which is exactly why they can
    # check that the log path agrees with the direct one against a third party.
    assert np.allclose(np.ravel(stats["logp(Q)"]), np.log(case["QEp"]), rtol=RTOL)


@pytest.mark.parametrize(
    "case",
    [case for case in CASES if case["method"] in Q_BASED_METHODS],
    ids=[case_id(case) for case in CASES if case["method"] in Q_BASED_METHODS],
)
def test_i2_and_h_match_metafor_where_the_definitions_coincide(case, metafor_dataset):
    """``I^2`` and ``H`` must match metafor's for ``FE`` and ``DL``.

    Both bounds are PyMARE's and not metafor's: PyMARE floors ``I^2`` at 0 and
    ``H`` at 1, as :footcite:t:`higgins2002quantifying` define them, while
    metafor reports ``H^2 = Q / df`` unfloored and so can print a value below
    one. Applying the floors to the reference rather than dropping the cases
    where they bite keeps the whole grid compared.

    References
    ----------
    .. footbibliography::
    """
    stats = fit(metafor_dataset, case).get_heterogeneity_stats()
    assert np.allclose(np.ravel(stats["I^2"]), max(0.0, case["I2"]), rtol=RTOL)
    assert np.allclose(np.ravel(stats["H"]), max(1.0, np.sqrt(case["H2"])), rtol=RTOL)


@pytest.mark.parametrize(
    "case",
    [case for case in CASES if case["method"] not in Q_BASED_METHODS],
    ids=[case_id(case) for case in CASES if case["method"] not in Q_BASED_METHODS],
)
def test_i2_and_h_are_the_q_based_definition(case, metafor_dataset):
    """Where the two disagree, PyMARE's pair must be the Q-based one.

    metafor switches to ``I^2 = 100 tau^2 / (tau^2 + v_t)`` and
    ``H^2 = tau^2 / v_t + 1`` for the estimators that are not ``FE`` or ``DL``,
    so its ``I^2`` depends on which tau^2 estimator was asked for and PyMARE's
    does not. Rather than pin the size of that gap -- which says nothing and
    would have to be re-pinned whenever an optimizer tolerance moved -- this
    asserts the shape of it: PyMARE's ``I^2`` and ``H`` for this case equal
    PyMARE's for the *fixed-effects* fit of the same design and model, because
    both are functions of the same Q.
    """
    fixed = dict(case, method="FE")
    reported = fit(metafor_dataset, case).get_heterogeneity_stats()
    q_based = fit(metafor_dataset, fixed).get_heterogeneity_stats()
    for key in ("Q", "I^2", "H"):
        assert np.allclose(np.ravel(reported[key]), np.ravel(q_based[key]), rtol=RTOL), key


@pytest.mark.parametrize(
    "case", RANDOM_EFFECT_CASES, ids=[case_id(case) for case in RANDOM_EFFECT_CASES]
)
def test_tau2_interval_matches_metafor(case, metafor_dataset):
    """The Q-profile interval must be metafor's ``confint`` bounds.

    :footcite:t:`viechtbauer2007confidence` inverted, which both implementations
    do by solving ``Q(tau^2) = chi^2_{1 - alpha/2}`` and ``= chi^2_{alpha/2}``
    for a root. The interval does not depend on the tau^2 point estimate, which
    is why every random-effects method in the grid is expected to produce the
    same pair and metafor's ``confint`` reports the same pair for each.

    References
    ----------
    .. footbibliography::
    """
    stats = fit(metafor_dataset, case).get_re_stats()
    assert np.allclose(np.ravel(stats["ci_l"]), case["tau2_ci_lb"], rtol=RTOL_PROFILE)
    assert np.allclose(np.ravel(stats["ci_u"]), case["tau2_ci_ub"], rtol=RTOL_PROFILE)


@pytest.mark.parametrize(
    "case",
    [case for case in HEDGES_CASES if not MODELS[case["model"]]],
    ids=[case_id(case) for case in HEDGES_CASES if not MODELS[case["model"]]],
)
def test_hedges_tau2_matches_metafor_without_moderators(case, metafor_dataset):
    """``Hedges`` tau^2 must be metafor's ``HE`` for an intercept-only model.

    Exactly, not approximately: the two expressions for the correction term are
    algebraically the same one when the intercept is the only predictor, so this
    holds to machine precision on all four designs.
    :func:`test_hedges_tau2_divergence_is_the_trace_term` covers what happens
    when a moderator is added.
    """
    assert np.allclose(np.ravel(fit(metafor_dataset, case).tau2), case["tau2"], rtol=RTOL)


@pytest.mark.parametrize("case", HEDGES_CASES, ids=[case_id(case) for case in HEDGES_CASES])
def test_hedges_tau2_divergence_is_the_trace_term(case, metafor_dataset):
    """Locate the ``HE`` divergence in the term each implementation subtracts.

    Both estimators are the excess of an unweighted mean squared error over an
    estimate of the mean sampling variance. They differ in the second term:
    metafor uses ``tr(PV) / (K - P)`` with ``P = I - X (X'X)^-1 X'``, PyMARE uses
    ``sum(v) / K``. Those coincide when ``X`` is just an intercept, since ``P``
    is then ``I - J/K`` and the trace is ``sum(v) (K - 1) / K``; with a moderator
    they do not, and PyMARE's tau^2 is out by up to 0.14 relative on this grid.

    Two assertions, which together say that and nothing more: metafor's own
    definition reimplemented here reproduces every pinned ``HE`` tau^2, and the
    two correction terms agree exactly when and only when there are no
    moderators. A test that instead pinned the size of the gap would be a record
    of PyMARE's current behaviour rather than a statement about either formula.
    """
    y, v, X = design_arrays(metafor_dataset, case)
    n_obs, n_preds = X.shape
    residual_maker = np.eye(n_obs) - X @ np.linalg.pinv(X.T @ X) @ X.T

    metafor_correction = np.trace(residual_maker @ np.diag(v)) / (n_obs - n_preds)
    pymare_correction = v.sum() / n_obs
    metafor_tau2 = max(
        0.0, (y @ residual_maker @ y - np.trace(residual_maker @ np.diag(v))) / (n_obs - n_preds)
    )

    assert np.allclose(metafor_tau2, case["tau2"], rtol=RTOL, atol=1e-12)
    if n_preds == 1:
        assert np.allclose(pymare_correction, metafor_correction, rtol=RTOL)
    else:
        assert not np.isclose(pymare_correction, metafor_correction, rtol=1e-6)


@pytest.mark.parametrize(
    "case",
    [c for c in PROFILED_CASES if (c["design"], c["model"]) != ML_BOUNDARY_CASE],
    ids=[case_id(c) for c in PROFILED_CASES if (c["design"], c["model"]) != ML_BOUNDARY_CASE],
)
def test_profiled_tau2_matches_metafor(case, metafor_dataset):
    """``ML`` and ``REML`` tau^2 must agree to the two search tolerances.

    Not to machine precision, and the gap is not evidence of a different
    objective: both implementations maximize the same likelihood by numerical
    search, and :data:`RTOL_PROFILED` is where the coarser of the two stops.
    What this rules out is the thing a loose tolerance might otherwise hide -- a
    different likelihood, a different parameterization, or a boundary handled
    differently -- since none of those would stay inside 1e-4 across twenty
    design-by-model cells.
    """
    assert np.allclose(
        np.ravel(fit(metafor_dataset, case).tau2),
        case["tau2"],
        rtol=RTOL_PROFILED,
        atol=ATOL_PROFILED,
    )


def test_ml_boundary_case_is_the_only_disagreement(metafor_dataset):
    """The excluded ``ML`` cell must still be excluded for the stated reason.

    The exclusion is worth having only if it stays a single named cell. This
    asserts both halves of the claim: that metafor is at the tau^2 = 0 boundary
    there while PyMARE is not, and that no other profiled cell in the grid
    misses :data:`RTOL_PROFILED` and :data:`ATOL_PROFILED` together.
    """
    boundary = [
        case
        for case in PROFILED_CASES
        if (case["design"], case["model"]) == ML_BOUNDARY_CASE and case["method"] == "ML"
    ]
    assert len(boundary) == 1
    assert boundary[0]["tau2"] == 0.0
    assert np.ravel(fit(metafor_dataset, boundary[0]).tau2)[0] > ATOL_PROFILED

    missed = sorted(
        case_id(case)
        for case in PROFILED_CASES
        if not np.allclose(
            np.ravel(fit(metafor_dataset, case).tau2),
            case["tau2"],
            rtol=RTOL_PROFILED,
            atol=ATOL_PROFILED,
        )
    )
    assert missed == [case_id(boundary[0])]


def test_reference_records_the_new_quantities():
    """Every case must carry the fields this module reads.

    The companion of ``test_reference_covers_every_combination`` in
    :mod:`pymare.tests.test_metafor_alignment`, which guards the grid. This
    guards the columns: a regenerated reference that dropped ``I2``, or emitted
    ``null`` for a Q that metafor does report, would otherwise turn these tests
    into no-ops rather than failures.
    """
    # int, not just float: "%.17g" writes an exact zero as `0`, so a design with
    # no excess dispersion records I2 as a JSON integer.
    numeric = (int, float)
    for case in REFERENCE["cases"]:
        for field in ("QE", "QEp", "I2", "H2"):
            assert isinstance(case[field], numeric), (case_id(case), field)
        # confint() has no tau^2 to bound under a fixed-effects model and is not
        # asked; every other method must produce a pair of finite bounds.
        bounds = (case["tau2_ci_lb"], case["tau2_ci_ub"])
        if case["method"] == "FE":
            assert bounds == (None, None), case_id(case)
        else:
            assert all(isinstance(bound, numeric) for bound in bounds), case_id(case)
            assert bounds[0] <= bounds[1], case_id(case)
