"""Alignment between PyMARE and the R package robumeta.

PyMARE's correlated-effects working model (``weight_scheme="rescale"``)
implements the estimator of :footcite:t:`hedges2010robust`, in the form given as
equations (7)-(9) of the robumeta paper (Fisher & Tipton, arXiv:1503.02220).
This module checks that the two implementations still agree, over every
combination of model, rho and variance column that both of them can express.

The reference values are pinned in ``data/robumeta_reference.json`` because
robumeta is an R package and cannot be a test dependency. The pin is kept honest
by regenerating it -- see :func:`pymare.tests.utils.load_robumeta_reference`.
"""

import numpy as np
import pytest

from pymare.estimators import DerSimonianLaird
from pymare.tests.utils import load_robumeta_reference

pytestmark = pytest.mark.robumeta

REFERENCE = load_robumeta_reference()

#: Tolerance on every quantity compared below. The two implementations do the
#: same arithmetic in a different order, so they agree to near machine
#: precision; a looser tolerance here would let a real divergence through.
RTOL = 1e-10


def case_id(case):
    """Name a case by the three knobs that distinguish it."""
    columns = "shared" if case["variances"].startswith("var_constant") else "varying"
    return f"{case['model']}-rho{case['rho']:g}-{columns}-v"


@pytest.mark.filterwarnings("ignore:Cluster-robust")
@pytest.mark.parametrize(
    "case", REFERENCE["cases"], ids=[case_id(case) for case in REFERENCE["cases"]]
)
def test_matches_robumeta_correlated_effects(case, robumeta_dataset):
    """The correlated-effects model must reproduce the implementation it cites.

    This pins far more than the tau^2 estimator: the coefficients come from the
    correlated-effects weights, the standard errors from the CR2 sandwich and
    the degrees of freedom from the Satterthwaite approximation, so agreement
    here exercises the whole path against
    :footcite:t:`hedges2010robust` as implemented by robumeta.

    Both variance columns are checked: one constant within a study, one varying
    sharply within it. PyMARE weights both the way robumeta does, so the two
    agree throughout rather than only where the weightings happen to coincide.
    """
    frame, designs = robumeta_dataset
    fitted = (
        DerSimonianLaird(weight_scheme="rescale", rho=case["rho"])
        .fit(
            y=frame["effect"].to_numpy()[:, None],
            v=frame[case["variances"]].to_numpy()[:, None],
            X=designs[case["model"]],
            g=frame["study"].to_numpy(),
        )
        .summary()
    )

    assert np.allclose(np.ravel(fitted.tau2), case["tau2"], rtol=RTOL, atol=0)
    assert np.allclose(np.ravel(fitted.fe_params), case["beta"], rtol=RTOL, atol=0)
    assert np.allclose(np.ravel(fitted.fe_se), case["se"], rtol=RTOL, atol=0)
    assert np.allclose(np.ravel(fitted.fe_dof), case["dof"], rtol=RTOL, atol=0)


def test_reference_covers_every_combination():
    """A dropped case would otherwise look like a passing suite.

    The reference is regenerated by a script that loops over the grid, so a
    case can go missing without any test failing. Checking the grid here means
    the alignment check cannot silently shrink.
    """
    cases = REFERENCE["cases"]
    keys = {(case["model"], case["rho"], case["variances"]) for case in cases}

    assert len(keys) == len(cases), "duplicate cases in the reference"
    assert keys == {
        (model, rho, variances)
        for model in ("intercept", "within", "both")
        for rho in (0.0, 0.4, 0.8, 1.0)
        for variances in ("var_constant_within_study", "var_within_study")
    }
