"""Utilities for the PyMARE test suite.

Helpers that are not fixtures and not tests. Fixtures belong in ``conftest.py``,
so this holds the plumbing that fixtures and parametrization both need -- most
importantly the reference values that cannot be recomputed at test time because
they come from another implementation.
"""

import json
import os.path as op


def get_test_data_path():
    """Return the path to the test data directory.

    Returns
    -------
    :obj:`str`
        Absolute path to ``pymare/tests/data``.
    """
    return op.abspath(op.join(op.dirname(__file__), "data"))


def load_robumeta_reference():
    """Load the reference values the R package robumeta produced.

    Returns
    -------
    :obj:`dict`
        The parsed contents of ``data/robumeta_reference.json``: a ``"source"``
        record naming the R and robumeta versions that produced the numbers, and
        a ``"cases"`` list holding one entry per (model, rho, variance column)
        combination.

    Notes
    -----
    robumeta is not a test dependency, so these numbers are pinned rather than
    recomputed on every run. ``validation/robumeta/regenerate.sh`` rewrites the
    file from the pinned R image, and the ``Check robumeta alignment`` workflow
    runs that script on every pull request and fails if anything moved -- which
    is what keeps a pinned file from quietly becoming a stale one.
    """
    with open(op.join(get_test_data_path(), "robumeta_reference.json")) as fobj:
        return json.load(fobj)


def cmdstan_is_available():
    """Report whether the Stan estimator can actually be run here.

    Returns
    -------
    :obj:`bool`
        True when ``cmdstanpy`` imports *and* it can find a CmdStan
        installation.

    Notes
    -----
    Both halves matter. ``cmdstanpy`` installs cleanly from PyPI without
    CmdStan, which is a C++ build rather than a Python package, so an import
    check alone would report an environment as ready when it can only fail.

    The failure this replaced was subtler still: the previous gate probed
    ``find_spec("pystan")``, but PyStan 3 is distributed as ``pystan`` and
    imported as ``stan``, so the probe was unsatisfiable and the estimator's
    only real test skipped everywhere, including in the CI job that existed to
    run it. A skip reads as a pass in a CI log, which is why the
    ``pytest_collection_modifyitems`` hook in ``conftest.py`` consults this
    function and fails the run wherever ``PYMARE_REQUIRE_CMDSTAN`` says Stan is
    expected.
    """
    try:
        import cmdstanpy
    except ImportError:
        return False

    try:
        cmdstanpy.cmdstan_path()
    except Exception:
        return False

    return True


#: Thresholds the Stan model's simulated performance has to meet. Applied in two
#: places against the same numbers: ``test_stan_estimators.py`` checks them
#: against the pinned ``data/stan_validation.json``, and
#: ``validation/stan/simulate.py --check`` checks them against a fresh run.
#:
#: ``min_coverage`` is a floor on the *worst* coefficient's share of 95% credible
#: intervals containing the true value; averaging across coefficients would let a
#: well-estimated intercept mask a badly estimated moderator. It sits well below
#: the nominal 0.95 because a minimum over coefficients is biased downward. 0.85
#: is between the worst honest measurement and the failures it has to reject --
#: ``validation/stan/README.md`` records both.
#:
#: ``max_beta_bias`` bounds the largest absolute bias across coefficients. It only
#: means anything because the harness holds the true coefficients fixed; with a
#: redrawn symmetric truth the signed errors average to zero for any estimator.
STAN_VALIDATION_THRESHOLDS = {
    "min_coverage": 0.85,
    "max_beta_bias": 0.10,
}

#: The design cells ``validation/stan/simulate.py`` is expected to report on.
#: Pinned here so that adding or renaming a cell fails the test that reads the
#: recorded results until the pinned file is regenerated, rather than quietly
#: leaving the new cell unchecked.
STAN_VALIDATION_CELLS = (
    "groups=5",
    "groups=20",
    "groups=50",
    "tau2=0",
    "tau2=0.1",
    "tau2=1",
    "singletons",
    "unequal groups",
    "sigma x0.1",
    "sigma x10",
    "1 predictor",
    "3 predictors",
    "unbalanced covariate",
    "unbalanced covariate, tau2=1",
)


def load_stan_validation():
    """Load the recorded simulation results for the Stan meta-regression model.

    Returns
    -------
    :obj:`dict`
        The parsed contents of ``data/stan_validation.json``: the provenance of
        the run and a ``"cells"`` list holding one entry per design cell, with
        that cell's measured bias, credible-interval coverage and divergence
        count.

    Notes
    -----
    Regenerated by ``validation/stan/simulate.py``, which takes about ten
    minutes, so the results are pinned rather than recomputed on every run --
    the same arrangement as :func:`load_robumeta_reference`.

    Unlike the robumeta reference, these numbers are stochastic, so the pin
    cannot be enforced by requiring the file not to move; a correct estimator
    produces slightly different numbers every run. What is enforced instead is
    ``STAN_VALIDATION_THRESHOLDS``, which is the claim the file exists to
    support.
    """
    with open(op.join(get_test_data_path(), "stan_validation.json")) as fobj:
        return json.load(fobj)
